apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq-service 5672; do echo 'waiting for rabbitmq'; sleep 2; done;",
            ]
      containers:
        - name: api
          image: contact-register-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "prod"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=mssql-service;User Id=sa;Password=$(MSSQL_SA_PASSWORD);TrustServerCertificate=True;"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: DOTNET_METRICS_EXPORTER
              value: "prometheus"
            - name: RabbitMq__HostName
              value: "rabbitmq-service"
          envFrom:
            - secretRef:
                name: mssql-secret
          resources:
            limits:
              memory: 512Mi
              cpu: "0.4"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
