apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus
          resources:
            limits:
              memory: 1Gi
              cpu: "0.4"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 3s
    scrape_configs:
    - job_name: 'api'
      static_configs:
      - targets: ['api-service:8080']
    - job_name: 'worker-storage'
      static_configs:
      - targets: ['worker-storage-service:8081']
    - job_name: 'worker-update'
      static_configs:
      - targets: ['worker-update-service:8082']
    - job_name: 'worker-delete'
      static_configs:
      - targets: ['worker-delete-service:8083']
    - job_name: 'rabbitmq'
      static_configs:
      - targets: ['rabbitmq-service:15692']
