apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-storage
  template:
    metadata:
      labels:
        app: worker-storage
    spec:
      initContainers:
        - name: wait-for-api
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until wget -q -T1 -O- http://api-service:8080/health; do echo waiting for api-service; sleep 2; done;",
            ]
      containers:
        - name: worker-storage
          image: contact-register-worker-storage
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "prod"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=mssql-service;User Id=sa;Password=$(MSSQL_SA_PASSWORD);TrustServerCertificate=True;"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8081"
            - name: DOTNET_METRICS_EXPORTER
              value: "prometheus"
            - name: RabbitMq__HostName
              value: "rabbitmq-service"
          envFrom:
            - secretRef:
                name: mssql-secret
          resources:
            limits:
              memory: 512Mi
              cpu: "0.4"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-storage-service
spec:
  selector:
    app: worker-storage
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
